apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  annotations:
    eks.amazonaws.com/role-arn: "give the arn or role for params"
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    component: cart
spec:
  serviceAccountName: cart
  containers:
    - name: cart
      image: 860050401100.dkr.ecr.us-east-1.amazonaws.com/cart:2.0.2
      volumeMounts:
        - mountPath: /params
          name: params
  initContainers:
    - name: aws-ssm-param-store
      image: 860050401100.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store:1.0.1
      args: ["sample:dev.docdb.pass"]
      volumeMounts:
        - mountPath: /params
          name: params
  volumes:
    - name: params
      emptyDir:
        sizeLimit: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    component: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080